COMPETITION_ID_MAPPING = {
    # Men's European Leagues
    "Premier League": 2,
    "Ligue 1": 7,
    "1. Bundesliga": 9,
    "La Liga": 11,
    "Serie A": 12,
    "Champions League": 16,
    "UEFA Europa League": 35,
    "Copa del Rey": 87,
    # Men's American Leagues
    "Major League Soccer": 44,
    "North American League": 116,
    "Liga Profesional": 81,
    # Men's International Competitions
    "FIFA World Cup": 43,
    "UEFA Euro": 55,
    "Copa America": 223,
    "African Cup of Nations": 1267,
    "FIFA U20 World Cup": 1470,
    # Women's Leagues or International Competitions
    "FA Women's Super League": 37,
    "NWSL": 49,
    "UEFA Women's Euro": 53,
    "Women's World Cup": 72,
    # Other Leagues
    "Indian Super league": 1238,
}

COMPETITION_INFO = {
    "Premier League" : {
        "competition_id": 2, 
        "name": "Premier League", 
        "country": "England", 
        "number_of_seasons": 2, 
        "seasons": {
            "2015/2016": {"season_id": 27, "number_of_matches": 380},
            "2003/2004": {"season_id": 44, "number_of_matches": 38},
        },
    },
    "Ligue 1" : {
        "competition_id": 7, 
        "name": "Ligue 1", 
        "country": "France", 
        "number_of_seasons": 3, 
        "seasons": {
            "2022/2023": {"season_id": 235, "number_of_matches": 32},
            "2021/2022": {"season_id": 108, "number_of_matches": 26},
            "2015/2016": {"season_id": 27, "number_of_matches": 377},
        },
    },
    "1. Bundesliga" : {
        "competition_id": 9, 
        "name": "1. Bundesliga", 
        "country": "Germany", 
        "number_of_seasons": 2, 
        "seasons": {
            "2023/2024": {"season_id": 281, "number_of_matches": 34},
            "2015/2016": {"season_id": 27, "number_of_matches": 306},
        },
    },
    "La Liga" : {
        "competition_id": 11, 
        "name": "La Liga", 
        "country": "Spain", 
        "number_of_seasons": 18, 
        "seasons": {
            "2020/2021": {"season_id": 90, "number_of_matches": 35},
            "2019/2020": {"season_id": 42, "number_of_matches": 33},
            "2018/2019": {"season_id": 4, "number_of_matches": 34},
            "2017/2018": {"season_id": 1, "number_of_matches": 36},
            "2016/2017": {"season_id": 2, "number_of_matches": 34},
            "2015/2016": {"season_id": 27, "number_of_matches": 380},
            "2014/2015": {"season_id": 26, "number_of_matches": 38},
            "2013/2014": {"season_id": 25, "number_of_matches": 31},
            "2012/2013": {"season_id": 24, "number_of_matches": 32},
            "2011/2012": {"season_id": 23, "number_of_matches": 37},
            "2010/2011": {"season_id": 22, "number_of_matches": 33},
            "2009/2010": {"season_id": 21, "number_of_matches": 35},
            "2008/2009": {"season_id": 41, "number_of_matches": 31},
            "2007/2008": {"season_id": 40, "number_of_matches": 28},
            "2006/2007": {"season_id": 39, "number_of_matches": 26},
            "2005/2006": {"season_id": 38, "number_of_matches": 17},
            "2004/2005": {"season_id": 37, "number_of_matches": 7},
            "1973/1974": {"season_id": 278, "number_of_matches": 1},
        },
    },
    "Serie A" : {
        "competition_id": 12, 
        "name": "Serie A", 
        "country": "Italy", 
        "number_of_seasons": 2, 
        "seasons": {
            "2015/2016": {"season_id": 27, "number_of_matches": 380},
            "1986/1987": {"season_id": 86, "number_of_matches": 1},
        },
    },
    "Champions League" : {
        "competition_id": 16, 
        "name": "Champions League", 
        "country": "Europe", 
        "number_of_seasons": 18, 
        "seasons": {
            "2018/2019": {"season_id": 4, "number_of_matches": 1},
            "2017/2018": {"season_id": 1, "number_of_matches": 1},
            "2016/2017": {"season_id": 2, "number_of_matches": 1},
            "2015/2016": {"season_id": 27, "number_of_matches": 1},
            "2014/2015": {"season_id": 26, "number_of_matches": 1},
            "2013/2014": {"season_id": 25, "number_of_matches": 1},
            "2012/2013": {"season_id": 24, "number_of_matches": 1},
            "2011/2012": {"season_id": 23, "number_of_matches": 1},
            "2010/2011": {"season_id": 22, "number_of_matches": 1},
            "2009/2010": {"season_id": 21, "number_of_matches": 1},
            "2008/2009": {"season_id": 41, "number_of_matches": 1},
            "2006/2007": {"season_id": 39, "number_of_matches": 1},
            "2004/2005": {"season_id": 37, "number_of_matches": 1},
            "2003/2004": {"season_id": 44, "number_of_matches": 1},
            "1999/2000": {"season_id": 76, "number_of_matches": 1},
            "1972/1973": {"season_id": 277, "number_of_matches": 1},
            "1971/1972": {"season_id": 71, "number_of_matches": 1},
            "1970/1971": {"season_id": 276, "number_of_matches": 1},
        },
    },
    "UEFA Europa League" : {
        "competition_id": 35, 
        "name": "UEFA Europa League", 
        "country": "Europe", 
        "number_of_seasons": 1, 
        "seasons": {
            "1988/1989": {"season_id": 75, "number_of_matches": 0},
        },
    },
    "Copa del Rey" : {
        "competition_id": 87, 
        "name": "Copa del Rey", 
        "country": "Spain", 
        "number_of_seasons": 3, 
        "seasons": {
            "1983/1984": {"season_id": 84, "number_of_matches": 0},
            "1982/1983": {"season_id": 268, "number_of_matches": 0},
            "1977/1978": {"season_id": 279, "number_of_matches": 0},
        },
    },
    "Major League Soccer" : {
        "competition_id": 44, 
        "name": "Major League Soccer", 
        "country": "United States of America", 
        "number_of_seasons": 1, 
        "seasons": {
            "2023": {"season_id": 107, "number_of_matches": 0},
        },
    },
    "North American League" : {
        "competition_id": 116, 
        "name": "North American League", 
        "country": "North and Central America", 
        "number_of_seasons": 1, 
        "seasons": {
            "1977": {"season_id": 68, "number_of_matches": 0},
        },
    },
    "Liga Profesional" : {
        "competition_id": 81, 
        "name": "Liga Profesional", 
        "country": "Argentina", 
        "number_of_seasons": 2, 
        "seasons": {
            "1997/1998": {"season_id": 48, "number_of_matches": 0},
            "1981": {"season_id": 275, "number_of_matches": 0},
        },
    },
    "FIFA World Cup" : {
        "competition_id": 43, 
        "name": "FIFA World Cup", 
        "country": "International", 
        "number_of_seasons": 8, 
        "seasons": {
            "2022": {"season_id": 106, "number_of_matches": 64},
            "2018": {"season_id": 3, "number_of_matches": 64},
            "1990": {"season_id": 55, "number_of_matches": 1},
            "1986": {"season_id": 54, "number_of_matches": 3},
            "1974": {"season_id": 51, "number_of_matches": 6},
            "1970": {"season_id": 272, "number_of_matches": 6},
            "1962": {"season_id": 270, "number_of_matches": 1},
            "1958": {"season_id": 269, "number_of_matches": 2},
        },
    },
    "UEFA Euro" : {
        "competition_id": 55, 
        "name": "UEFA Euro", 
        "country": "Europe", 
        "number_of_seasons": 2, 
        "seasons": {
            "2024": {"season_id": 282, "number_of_matches": 51},
            "2020": {"season_id": 43, "number_of_matches": 51},
        },
    },
    "Copa America" : {
        "competition_id": 223, 
        "name": "Copa America", 
        "country": "South America", 
        "number_of_seasons": 1, 
        "seasons": {
            "2024": {"season_id": 282, "number_of_matches": 32},
        },
    },
    "African Cup of Nations" : {
        "competition_id": 1267, 
        "name": "African Cup of Nations", 
        "country": "Africa", 
        "number_of_seasons": 1, 
        "seasons": {
            "2023": {"season_id": 107, "number_of_matches": 52},
        },
    },
    "FIFA U20 World Cup" : {
        "competition_id": 1470, 
        "name": "FIFA U20 World Cup", 
        "country": "International", 
        "number_of_seasons": 1, 
        "seasons": {
            "1979": {"season_id": 274, "number_of_matches": 0},
        },
    },
    "FA Women's Super League" : {
        "competition_id": 37, 
        "name": "FA Women's Super League", 
        "country": "England", 
        "number_of_seasons": 3, 
        "seasons": {
            "2020/2021": {"season_id": 90, "number_of_matches": 131},
            "2019/2020": {"season_id": 42, "number_of_matches": 87},
            "2018/2019": {"season_id": 4, "number_of_matches": 108},
        },
    },
    "NWSL" : {
        "competition_id": 49, 
        "name": "NWSL", 
        "country": "United States of America", 
        "number_of_seasons": 1, 
        "seasons": {
            "2018": {"season_id": 3, "number_of_matches": 0},
        },
    },
    "UEFA Women's Euro" : {
        "competition_id": 53, 
        "name": "UEFA Women's Euro", 
        "country": "Europe", 
        "number_of_seasons": 2, 
        "seasons": {
            "2025": {"season_id": 315, "number_of_matches": 31},
            "2022": {"season_id": 106, "number_of_matches": 31},
        },
    },
    "Women's World Cup" : {
        "competition_id": 72, 
        "name": "Women's World Cup", 
        "country": "International", 
        "number_of_seasons": 2, 
        "seasons": {
            "2023": {"season_id": 107, "number_of_matches": 64},
            "2019": {"season_id": 30, "number_of_matches": 52},
        },
    },
    "Indian Super league" : {
        "competition_id": 1238, 
        "name": "Indian Super league", 
        "country": "India", 
        "number_of_seasons": 1, 
        "seasons": {
            "2021/2022": {"season_id": 108, "number_of_matches": 0},
        },
    },
}
